# Site settings
title: Jinzhi Lei
email: jzlei@mail.tsinghua.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  个人介绍
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jzlei.github.io" # the base hostname & protocol for your site
github_username:  jzlei
orcid_id: 编号
google_scholar_id: 谷歌学术编号

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Associate Researcher"
excerpt_separator: "<!--more-->"

# SEO stuff
# 下面的应该和搜索引擎能否搜到个人博客的配置
google_site_verification: ""
bing_webmastertools_id: ""

plugins:
  - jekyll-sitemap
